server.port=8080
spring.application.name=payment-app

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/paymentapp
spring.datasource.username=sethuvenkataraman
spring.datasource.password=

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
