server.port=8080
spring.application.name=payment-app

# PostgreSQL — env vars override locals in prod (set via Elastic Beanstalk config)
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/paymentapp}
spring.datasource.username=${DB_USERNAME:sethuvenkataraman}
spring.datasource.password=${DB_PASSWORD:}

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
